-- canonical ingredients seed

insert into canonical_ingredients (canonical_name, category, default_expiration_days, common_units, synonyms, nutrition) values
-- produce
('bananas', 'produce', 7, array['count','lb'], array['banana','plantain'], '{"calories":89,"protein_g":1.1,"carbs_g":22.8,"fat_g":0.3,"fiber_g":2.6}'::jsonb),
('apples', 'produce', 21, array['count','lb'], array['apple','gala','fuji','granny smith'], '{"calories":52,"protein_g":0.3,"carbs_g":13.8,"fat_g":0.2,"fiber_g":2.4}'::jsonb),
('oranges', 'produce', 14, array['count','lb'], array['orange','navel','valencia'], '{"calories":47,"protein_g":0.9,"carbs_g":11.8,"fat_g":0.1,"fiber_g":2.4}'::jsonb),
('lemons', 'produce', 14, array['count'], array['lemon'], '{"calories":29,"protein_g":1.1,"carbs_g":9.3,"fat_g":0.3}'::jsonb),
('limes', 'produce', 14, array['count'], array['lime'], '{"calories":30,"protein_g":0.7,"carbs_g":10.5,"fat_g":0.2}'::jsonb),
('strawberries', 'produce', 5, array['oz','lb','pint'], array['strawberry'], '{"calories":32,"protein_g":0.7,"carbs_g":7.7,"fat_g":0.3,"fiber_g":2.0}'::jsonb),
('blueberries', 'produce', 7, array['oz','pint'], array['blueberry'], '{"calories":57,"protein_g":0.7,"carbs_g":14.5,"fat_g":0.3,"fiber_g":2.4}'::jsonb),
('grapes', 'produce', 14, array['lb','oz'], array['grape','red grapes','green grapes'], '{"calories":69,"protein_g":0.7,"carbs_g":18.1,"fat_g":0.2}'::jsonb),
('lettuce', 'produce', 7, array['head','count'], array['romaine','iceberg','butter lettuce'], '{"calories":15,"protein_g":1.4,"carbs_g":2.9,"fat_g":0.2}'::jsonb),
('spinach', 'produce', 5, array['oz','lb','bunch'], array['baby spinach'], '{"calories":23,"protein_g":2.9,"carbs_g":3.6,"fat_g":0.4,"fiber_g":2.2}'::jsonb),
('kale', 'produce', 7, array['oz','bunch'], array['curly kale','tuscan kale','lacinato'], '{"calories":35,"protein_g":2.9,"carbs_g":4.4,"fat_g":1.5}'::jsonb),
('carrots', 'produce', 21, array['lb','count'], array['carrot','baby carrots'], '{"calories":41,"protein_g":0.9,"carbs_g":9.6,"fat_g":0.2,"fiber_g":2.8}'::jsonb),
('celery', 'produce', 14, array['count','bunch'], array['celery stalk'], '{"calories":16,"protein_g":0.7,"carbs_g":3.0,"fat_g":0.2}'::jsonb),
('tomatoes', 'produce', 7, array['lb','count'], array['tomato','roma','beefsteak','cherry tomatoes'], '{"calories":18,"protein_g":0.9,"carbs_g":3.9,"fat_g":0.2,"fiber_g":1.2}'::jsonb),
('cucumbers', 'produce', 7, array['count'], array['cucumber','english cucumber','persian cucumber'], '{"calories":15,"protein_g":0.7,"carbs_g":3.6,"fat_g":0.1}'::jsonb),
('bell peppers', 'produce', 14, array['count'], array['bell pepper','red bell pepper','green bell pepper','yellow bell pepper'], '{"calories":31,"protein_g":1.0,"carbs_g":6.0,"fat_g":0.3}'::jsonb),
('yellow onions', 'produce', 30, array['count','lb'], array['yellow onion','onion'], '{"calories":40,"protein_g":1.1,"carbs_g":9.3,"fat_g":0.1}'::jsonb),
('red onions', 'produce', 30, array['count'], array['red onion'], '{"calories":40,"protein_g":1.1,"carbs_g":9.3,"fat_g":0.1}'::jsonb),
('garlic', 'produce', 60, array['count','head','clove'], array['garlic head','garlic clove'], '{"calories":149,"protein_g":6.4,"carbs_g":33.1,"fat_g":0.5}'::jsonb),
('ginger', 'produce', 30, array['oz','knob'], array['ginger root'], null),
('russet potatoes', 'produce', 30, array['lb','count'], array['potato','russet','baking potato'], '{"calories":77,"protein_g":2.0,"carbs_g":17.5,"fat_g":0.1}'::jsonb),
('sweet potatoes', 'produce', 30, array['lb','count'], array['sweet potato','yam'], '{"calories":86,"protein_g":1.6,"carbs_g":20.1,"fat_g":0.1}'::jsonb),
('broccoli', 'produce', 7, array['head','lb','count'], array['broccoli florets'], '{"calories":34,"protein_g":2.8,"carbs_g":6.6,"fat_g":0.4}'::jsonb),
('mushrooms', 'produce', 5, array['oz','lb'], array['button mushrooms','cremini','baby bella','portobello'], '{"calories":22,"protein_g":3.1,"carbs_g":3.3,"fat_g":0.3}'::jsonb),
('zucchini', 'produce', 7, array['count','lb'], array['courgette','summer squash'], '{"calories":17,"protein_g":1.2,"carbs_g":3.1,"fat_g":0.3}'::jsonb),
('avocados', 'produce', 5, array['count'], array['avocado','hass avocado'], '{"calories":160,"protein_g":2.0,"carbs_g":8.5,"fat_g":14.7,"fiber_g":6.7}'::jsonb),
('cilantro', 'produce', 5, array['bunch'], array['coriander','coriander leaf'], null),
-- dairy
('whole milk', 'dairy', 7, array['oz','cup','gallon','quart'], array['milk','2% milk','skim milk'], '{"calories":61,"protein_g":3.2,"carbs_g":4.8,"fat_g":3.3}'::jsonb),
('butter', 'dairy', 30, array['stick','oz','lb','tbsp'], array['unsalted butter','salted butter'], '{"calories":717,"protein_g":0.9,"carbs_g":0.1,"fat_g":81.1}'::jsonb),
('eggs', 'dairy', 28, array['count','dozen'], array['egg','large eggs'], '{"calories":155,"protein_g":13.0,"carbs_g":1.1,"fat_g":11.0}'::jsonb),
('greek yogurt', 'dairy', 14, array['oz','cup','container'], array['plain greek yogurt','vanilla greek yogurt'], '{"calories":59,"protein_g":10.0,"carbs_g":3.6,"fat_g":0.4}'::jsonb),
('cheddar cheese', 'dairy', 30, array['oz','lb'], array['cheddar','sharp cheddar','mild cheddar'], '{"calories":403,"protein_g":24.9,"carbs_g":1.3,"fat_g":33.1}'::jsonb),
('mozzarella cheese', 'dairy', 30, array['oz','lb','ball'], array['mozzarella','fresh mozzarella','shredded mozzarella'], '{"calories":300,"protein_g":22.2,"carbs_g":2.2,"fat_g":22.4}'::jsonb),
('cream cheese', 'dairy', 21, array['oz','block'], array['philadelphia cream cheese'], '{"calories":342,"protein_g":6.2,"carbs_g":4.1,"fat_g":34.0}'::jsonb),
('sour cream', 'dairy', 21, array['oz','tbsp','container'], array['sour cream'], null),
('heavy cream', 'dairy', 14, array['cup','oz','tbsp'], array['heavy whipping cream','whipping cream'], null),
-- meat
('chicken breast', 'meat', 3, array['lb','oz','count'], array['boneless skinless chicken breast','chicken'], '{"calories":165,"protein_g":31.0,"carbs_g":0,"fat_g":3.6}'::jsonb),
('chicken thighs', 'meat', 3, array['lb','oz','count'], array['chicken thigh','boneless chicken thigh'], '{"calories":209,"protein_g":26.0,"carbs_g":0,"fat_g":11.0}'::jsonb),
('ground beef', 'meat', 2, array['lb','oz'], array['ground beef 80/20','ground beef 90/10','ground chuck'], '{"calories":254,"protein_g":17.0,"carbs_g":0,"fat_g":20.0}'::jsonb),
('ground turkey', 'meat', 2, array['lb','oz'], array['lean ground turkey','ground turkey 93/7'], '{"calories":148,"protein_g":19.7,"carbs_g":0,"fat_g":7.4}'::jsonb),
('bacon', 'meat', 14, array['lb','oz','slice'], array['bacon strips'], '{"calories":541,"protein_g":37.0,"carbs_g":1.4,"fat_g":42.0}'::jsonb),
('italian sausage', 'meat', 3, array['lb','oz','link'], array['sausage','sweet italian sausage','hot italian sausage'], null),
('pork chops', 'meat', 3, array['lb','count'], array['boneless pork chops','bone-in pork chops'], null),
-- seafood
('salmon', 'seafood', 2, array['lb','oz','fillet'], array['atlantic salmon','salmon fillet','wild salmon'], '{"calories":208,"protein_g":20.4,"carbs_g":0,"fat_g":13.4}'::jsonb),
('shrimp', 'seafood', 2, array['lb','oz','count'], array['raw shrimp','peeled shrimp','frozen shrimp'], '{"calories":99,"protein_g":24.0,"carbs_g":0.2,"fat_g":0.3}'::jsonb),
('tuna', 'seafood', 2, array['lb','oz','steak'], array['ahi tuna','yellowfin tuna','tuna steak'], '{"calories":144,"protein_g":23.3,"carbs_g":0,"fat_g":4.9}'::jsonb),
-- pantry
('white rice', 'pantry', 365, array['cup','lb','oz'], array['long grain white rice','jasmine rice','basmati rice'], '{"calories":130,"protein_g":2.7,"carbs_g":28.0,"fat_g":0.3}'::jsonb),
('brown rice', 'pantry', 180, array['cup','lb'], array['brown rice','long grain brown rice'], '{"calories":111,"protein_g":2.6,"carbs_g":23.0,"fat_g":0.9}'::jsonb),
('pasta', 'pantry', 730, array['lb','oz'], array['spaghetti','penne','rotini','rigatoni','fettuccine','linguine'], '{"calories":131,"protein_g":5.0,"carbs_g":25.0,"fat_g":1.1}'::jsonb),
('all-purpose flour', 'pantry', 180, array['cup','lb'], array['flour','ap flour','wheat flour'], '{"calories":364,"protein_g":10.3,"carbs_g":76.3,"fat_g":1.0}'::jsonb),
('white sugar', 'pantry', 730, array['cup','lb'], array['sugar','granulated sugar','cane sugar'], '{"calories":387,"protein_g":0,"carbs_g":99.8,"fat_g":0}'::jsonb),
('brown sugar', 'pantry', 365, array['cup','lb'], array['light brown sugar','dark brown sugar'], '{"calories":380,"protein_g":0.1,"carbs_g":98.1,"fat_g":0}'::jsonb),
('table salt', 'pantry', 3650, array['tsp','tbsp','cup'], array['salt','iodized salt','sea salt','kosher salt'], null),
('olive oil', 'pantry', 730, array['cup','tbsp','oz','bottle'], array['extra virgin olive oil','evoo','light olive oil'], '{"calories":884,"protein_g":0,"carbs_g":0,"fat_g":100.0}'::jsonb),
('vegetable oil', 'pantry', 365, array['cup','tbsp','oz','bottle'], array['canola oil','sunflower oil','corn oil'], null),
('soy sauce', 'pantry', 1095, array['tbsp','cup','bottle'], array['light soy sauce','dark soy sauce','tamari'], null),
('balsamic vinegar', 'pantry', 1095, array['tbsp','cup','bottle'], array['balsamic'], null),
('ketchup', 'pantry', 365, array['tbsp','cup','bottle'], array['catsup','tomato ketchup','heinz ketchup'], null),
('peanut butter', 'pantry', 365, array['tbsp','cup','jar'], array['creamy peanut butter','crunchy peanut butter'], '{"calories":588,"protein_g":25.0,"carbs_g":20.0,"fat_g":50.0}'::jsonb),
('rolled oats', 'pantry', 365, array['cup','oz','lb'], array['oats','old-fashioned oats','quick oats','steel cut oats'], '{"calories":389,"protein_g":16.9,"carbs_g":66.3,"fat_g":6.9}'::jsonb),
('white bread', 'pantry', 7, array['slice','loaf'], array['sliced bread','sandwich bread'], '{"calories":265,"protein_g":9.0,"carbs_g":49.0,"fat_g":3.2}'::jsonb),
('flour tortillas', 'pantry', 14, array['count','pack'], array['tortilla','burrito tortilla'], null),
('black beans', 'pantry', 1095, array['can','oz','cup'], array['canned black beans'], '{"calories":132,"protein_g":8.9,"carbs_g":23.7,"fat_g":0.5}'::jsonb),
('kidney beans', 'pantry', 1095, array['can','oz','cup'], array['canned kidney beans','red kidney beans'], null),
('garbanzo beans', 'pantry', 1095, array['can','oz','cup'], array['chickpeas','canned chickpeas'], '{"calories":164,"protein_g":8.9,"carbs_g":27.4,"fat_g":2.6}'::jsonb),
('diced tomatoes', 'pantry', 1095, array['can','oz'], array['canned diced tomatoes','crushed tomatoes'], null),
('tomato paste', 'pantry', 1095, array['can','oz','tbsp'], array['canned tomato paste'], null),
('chicken broth', 'pantry', 730, array['cup','oz','carton'], array['chicken stock','low-sodium chicken broth'], null),
-- frozen
('frozen mixed vegetables', 'frozen', 365, array['lb','oz','bag'], array['mixed vegetables','frozen veggies'], null),
('frozen berries', 'frozen', 365, array['lb','oz','bag'], array['frozen blueberries','frozen strawberries','frozen mixed berries'], null),
('vanilla ice cream', 'frozen', 60, array['pint','quart','gallon'], array['ice cream'], '{"calories":207,"protein_g":3.5,"carbs_g":24.0,"fat_g":11.0}'::jsonb),
-- spices
('black pepper', 'spices', 1095, array['tsp','tbsp','oz','grinder'], array['ground black pepper','black peppercorns','peppercorns'], null),
('ground cumin', 'spices', 1095, array['tsp','tbsp','oz','jar'], array['cumin'], null),
('paprika', 'spices', 1095, array['tsp','tbsp','oz'], array['sweet paprika','smoked paprika'], null),
('chili powder', 'spices', 1095, array['tsp','tbsp','oz'], array['chili'], null),
('dried oregano', 'spices', 1095, array['tsp','tbsp','oz'], array['oregano'], null),
('dried basil', 'spices', 1095, array['tsp','tbsp','oz'], array['basil'], null),
('ground cinnamon', 'spices', 1095, array['tsp','tbsp','oz'], array['cinnamon','cinnamon stick'], null),
('garlic powder', 'spices', 1095, array['tsp','tbsp','oz'], array['granulated garlic'], null),
('onion powder', 'spices', 1095, array['tsp','tbsp','oz'], array['granulated onion'], null),
('red pepper flakes', 'spices', 1095, array['tsp','tbsp','oz'], array['crushed red pepper','chili flakes'], null),
('vanilla extract', 'spices', 1825, array['tsp','tbsp','oz','bottle'], array['pure vanilla extract','imitation vanilla'], null),
-- beverages
('orange juice', 'beverages', 14, array['cup','oz','quart','gallon'], array['oj','fresh orange juice','tropicana'], null),
('ground coffee', 'beverages', 30, array['oz','lb','bag','scoop'], array['coffee','medium roast coffee','dark roast coffee'], null),
('whole bean coffee', 'beverages', 60, array['oz','lb','bag'], array['coffee beans'], null),
('tea bags', 'beverages', 730, array['count','box'], array['tea','black tea','green tea','herbal tea'], null),
('almond milk', 'beverages', 14, array['cup','oz','carton'], array['unsweetened almond milk','vanilla almond milk'], '{"calories":17,"protein_g":0.6,"carbs_g":1.5,"fat_g":1.2}'::jsonb),
-- bakery
('bagels', 'bakery', 5, array['count','pack'], array['bagel','everything bagel','plain bagel'], null),
('english muffins', 'bakery', 7, array['count','pack'], array['english muffin'], null),
-- household
('paper towels', 'household', 3650, array['roll','pack'], array['paper towel'], null),
('toilet paper', 'household', 3650, array['roll','pack'], array['tp','toilet tissue'], null),
('dish soap', 'household', 1095, array['oz','bottle'], array['dishwashing liquid','dawn dish soap'], null),
('laundry detergent', 'household', 1095, array['oz','bottle','load'], array['tide','liquid detergent'], null);
